apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulso-canary
  namespace: argocd
spec:
  project: pulso-rollouts
  source:
    repoURL: https://github.com/felipef2s/pulso-config.git
    targetRevision: main
    path: rollouts/canary
  destination:
    server: https://kubernetes.default.svc
    namespace: pulso-canary
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
